apiVersion: v1
kind: PersistentVolume
metadata:
  name: it-asset-register-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/ubuntu/it-asset-register/k8s-data
    type: DirectoryOrCreate
